[package]
name = "trc20_adrrgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsecp256k1 = "0.7.1"
rand = "0.8"
hex = "0.4"
sha2 = "0.10"
sha3 = "0.10"
base58 = "0.2"
